import os

readme = r"""# Vibe Coding Knowledge Base 🚀

Kurátorovaná kolekce TOP tier technické dokumentace a praktických příkladů pro vibe coding a AI-assisted development.

**Last updated:** 2025-12-15
**Total:** 31+ files, ~272 KB pure knowledge

---

## 📚 Zdroje

### ✅ 1. Claude Code Documentation
**Path:** `claude-code/`
**Files:** 15 markdown docs
**Size:** ~138 KB

**Topics:**
- Getting Started (Overview, Quickstart, Common Workflows)
- Build (MCP, Hooks, Plugins, Subagents)
- CLI (Reference, Interactive Mode, Slash Commands)
- Configuration (Settings, Memory, Status Line)

**Start:** [`claude-code/INDEX.md`](claude-code/INDEX.md)

---

### ✅ 2. Anthropic Cookbook
**Path:** `anthropic-cookbook/`
**Files:** 8 converted Jupyter notebooks
**Size:** ~78 KB

**Topics:** Getting Started, Agent Patterns, Skills, Advanced techniques

**Start:** [`anthropic-cookbook/INDEX.md`](anthropic-cookbook/INDEX.md)

---

### ✅ 3. Awesome Vibe Coding
**Path:** `awesome-vibe-coding/`
**Files:** 2 curated lists
**Size:** ~20 KB

**Topics:** Best practices, Context engineering, Tool comparisons

**Start:** [`awesome-vibe-coding/INDEX.md`](awesome-vibe-coding/INDEX.md)

---

### ✅ 4. AIFirst.cz (Czech)
**Path:** `aifirst/`
**Files:** 6 practical articles
**Size:** ~36 KB
**Language:** 🇨🇿 Czech

**Topics:** Vibe coding prakticky, Cursor 2.0, Claude Code + Figma

**Start:** [`aifirst/INDEX.md`](aifirst/INDEX.md)

---

## 📊 Summary

| Zdroj | Soubory | Velikost | Status |
|-------|---------|----------|--------|
| Claude Code | 15 | ~138 KB | ✅ Done |
| Anthropic Cookbook | 8 | ~78 KB | ✅ Done |
| Awesome Vibe Coding | 2 | ~20 KB | ✅ Done |
| AIFirst | 6 | ~36 KB | ✅ Done |
| **TOTAL** | **31** | **~272 KB** | ✅ Complete |

---

*Generated by Vibe Coding KB Builder - 2025-12-15*
"""

with open(r'C:\kb\README.md', 'w', encoding='utf-8') as f:
    f.write(readme)

print("✅ C:\\kb\\README.md updated!")
